import type { Order } from "@/features/orders/types"
import { useState, useEffect } from "react"

const mockOrders: Order[] = [
  {
    id: "1",
    customerName: "Ana Silva",
    deliveryDate: "2026-03-24",
    deliveryTime: "09:00",
    address: "Rua das Flores, 123",
    description: "2 Ovos de Colher (Ninho), 1 Ovo 500g (Amargo)",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "2",
    customerName: "Bruno Oliveira",
    deliveryDate: "2026-03-24",
    deliveryTime: "09:30",
    address: "Av. Brasil, 900",
    description: "1 Ovo Trufado Maracujá",
    status: "Delivered",
    orderDate: "2026-03-21",
  },
  {
    id: "3",
    customerName: "Carla Souza",
    deliveryDate: "2026-03-24",
    deliveryTime: "10:00",
    address: "Rua Piauí, 45",
    description: "3 Ovos Kids (Surpresa)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "4",
    customerName: "Diego Santos",
    deliveryDate: "2026-03-24",
    deliveryTime: "10:15",
    address: "Travessa da Paz, 12",
    description: "1 Ovo 1kg ao Leite",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "5",
    customerName: "Elena Rodrigues",
    deliveryDate: "2026-03-24",
    deliveryTime: "11:00",
    address: "Rua XV de Novembro, 200",
    description: "2 Ovos de Colher (Pistache)",
    status: "Delivered",
    orderDate: "2026-03-15",
  },
  {
    id: "6",
    customerName: "Fabricio Costa",
    deliveryDate: "2026-03-24",
    deliveryTime: "11:30",
    address: "Rua Goiás, 88",
    description: "1 Ovo Crocante 500g",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "7",
    customerName: "Giovana Melo",
    deliveryDate: "2026-03-24",
    deliveryTime: "13:00",
    address: "Av. Central, 1010",
    description: "5 Mini Ovos Sortidos",
    status: "Pending",
    orderDate: "2026-03-18",
  },
  {
    id: "8",
    customerName: "Henrique Lima",
    deliveryDate: "2026-03-24",
    deliveryTime: "13:30",
    address: "Rua Sergipe, 33",
    description: "1 Ovo de Colher (Morango)",
    status: "Delivered",
    orderDate: "2026-03-23",
  },
  {
    id: "9",
    customerName: "Isabela Rocha",
    deliveryDate: "2026-03-24",
    deliveryTime: "14:00",
    address: "Alameda das Palmeiras, 5",
    description: "2 Ovos Brancos 250g",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "10",
    customerName: "João Pedro",
    deliveryDate: "2026-03-24",
    deliveryTime: "14:45",
    address: "Rua Amazonas, 777",
    description: "1 Ovo 70% Cacau",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "11",
    customerName: "Kelly Vieira",
    deliveryDate: "2026-03-24",
    deliveryTime: "15:00",
    address: "Rua Curitiba, 102",
    description: "1 Caixa de Bombons Artesanais",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "12",
    customerName: "Lucas Mendes",
    deliveryDate: "2026-03-24",
    deliveryTime: "15:30",
    address: "Rua São Paulo, 400",
    description: "2 Ovos Trufados Avelã",
    status: "Delivered",
    orderDate: "2026-03-19",
  },
  {
    id: "13",
    customerName: "Mariana Alencar",
    deliveryDate: "2026-03-24",
    deliveryTime: "16:00",
    address: "Rua Rio de Janeiro, 15",
    description: "1 Ovo de Colher (Brownie)",
    status: "Pending",
    orderDate: "2026-03-21",
  },
  {
    id: "14",
    customerName: "Nivaldo Ferreira",
    deliveryDate: "2026-03-24",
    deliveryTime: "16:30",
    address: "Av. das Nações, 50",
    description: "4 Ovos de Colher (Diversos)",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "15",
    customerName: "Otávio Augusto",
    deliveryDate: "2026-03-24",
    deliveryTime: "17:00",
    address: "Rua Mato Grosso, 99",
    description: "1 Ovo 500g Amargo",
    status: "Delivered",
    orderDate: "2026-03-22",
  },
  {
    id: "16",
    customerName: "Patrícia Amaral",
    deliveryDate: "2026-03-24",
    deliveryTime: "17:30",
    address: "Rua Bahia, 120",
    description: "2 Ovos Kids Dragão",
    status: "Pending",
    orderDate: "2026-03-19",
  },
  {
    id: "17",
    customerName: "Quintino Gomes",
    deliveryDate: "2026-03-24",
    deliveryTime: "18:00",
    address: "Rua Alagoas, 21",
    description: "1 Ovo de Colher (Red Velvet)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "18",
    customerName: "Rafael Vitti",
    deliveryDate: "2026-03-24",
    deliveryTime: "18:15",
    address: "Rua Paraíba, 44",
    description: "1 Ovo Trufado Doce de Leite",
    status: "Pending",
    orderDate: "2026-03-21",
  },
  {
    id: "19",
    customerName: "Sabrina Sato",
    deliveryDate: "2026-03-24",
    deliveryTime: "18:45",
    address: "Av. Paulista, 1000",
    description: "3 Ovos de Colher (Ninho c/ Nutella)",
    status: "Delivered",
    orderDate: "2026-03-18",
  },
  {
    id: "20",
    customerName: "Tiago Iorc",
    deliveryDate: "2026-03-24",
    deliveryTime: "19:00",
    address: "Rua Ceará, 30",
    description: "1 Ovo 1kg Branco",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "21",
    customerName: "Ursula Corbero",
    deliveryDate: "2026-03-24",
    deliveryTime: "19:30",
    address: "Rua Rio Grande do Sul, 12",
    description: "2 Ovos de Colher (Brigadeiro)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "22",
    customerName: "Vitor Kley",
    deliveryDate: "2026-03-24",
    deliveryTime: "20:00",
    address: "Rua Santa Catarina, 88",
    description: "1 Ovo Trufado Limão Siciliano",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "23",
    customerName: "Wagner Moura",
    deliveryDate: "2026-03-24",
    deliveryTime: "20:30",
    address: "Rua Paraná, 500",
    description: "1 Ovo de Colher (Paçoca)",
    status: "Delivered",
    orderDate: "2026-03-21",
  },
  {
    id: "24",
    customerName: "Xuxa Meneghel",
    deliveryDate: "2026-03-25",
    deliveryTime: "08:00",
    address: "Av. Atlântica, 200",
    description: "10 Mini Ovos Veganos",
    status: "Pending",
    orderDate: "2026-03-15",
  },
  {
    id: "25",
    customerName: "Yasmim Brunet",
    deliveryDate: "2026-03-25",
    deliveryTime: "09:00",
    address: "Rua Rio de Janeiro, 300",
    description: "2 Ovos de Colher (Fit)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "26",
    customerName: "Zeca Pagodinho",
    deliveryDate: "2026-03-24",
    deliveryTime: "21:00",
    address: "Rua do Samba, 10",
    description: "1 Ovo Recheado de Cerveja",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "27",
    customerName: "Alice no País",
    deliveryDate: "2026-03-24",
    deliveryTime: "10:30",
    address: "Rua do Chá, 01",
    description: "1 Ovo de Colher (Cartas)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "28",
    customerName: "Beto Carreiro",
    deliveryDate: "2026-03-24",
    deliveryTime: "11:15",
    address: "Rua do Parque, 55",
    description: "2 Ovos Grandes ao Leite",
    status: "Delivered",
    orderDate: "2026-03-20",
  },
  {
    id: "29",
    customerName: "Caetano Veloso",
    deliveryDate: "2026-03-24",
    deliveryTime: "14:15",
    address: "Rua Tropicalia, 67",
    description: "1 Ovo Leãozinho 250g",
    status: "Pending",
    orderDate: "2026-03-21",
  },
  {
    id: "30",
    customerName: "Duda Beat",
    deliveryDate: "2026-03-24",
    deliveryTime: "15:45",
    address: "Rua do Recife, 81",
    description: "1 Ovo de Colher (Bolo de Rolo)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "31",
    customerName: "Emicida",
    deliveryDate: "2026-03-24",
    deliveryTime: "16:15",
    address: "Rua AmarElo, 10",
    description: "1 Ovo Lab Fantasma 500g",
    status: "Delivered",
    orderDate: "2026-03-22",
  },
  {
    id: "32",
    customerName: "Fernanda Montenegro",
    deliveryDate: "2026-03-24",
    deliveryTime: "17:45",
    address: "Av. Central, 1",
    description: "1 Ovo de Colher (Clássico)",
    status: "Pending",
    orderDate: "2026-03-19",
  },
  {
    id: "33",
    customerName: "Gisele Bündchen",
    deliveryDate: "2026-03-24",
    deliveryTime: "08:30",
    address: "Rua da Moda, 90",
    description: "1 Ovo de Colher (Gojiberry)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "34",
    customerName: "Humberto Gessinger",
    deliveryDate: "2026-03-24",
    deliveryTime: "12:45",
    address: "Rua Infinita, 38",
    description: "1 Ovo Crocante G",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "35",
    customerName: "Iza",
    deliveryDate: "2026-03-24",
    deliveryTime: "19:45",
    address: "Rua Dona de Mim, 100",
    description: "1 Ovo de Colher (Pesadão)",
    status: "Delivered",
    orderDate: "2026-03-21",
  },
  {
    id: "36",
    customerName: "Jão",
    deliveryDate: "2026-03-24",
    deliveryTime: "20:15",
    address: "Rua Pirata, 22",
    description: "2 Ovos de Colher (Rum)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "37",
    customerName: "Lulu Santos",
    deliveryDate: "2026-03-24",
    deliveryTime: "09:15",
    address: "Rua da Tempos Modernos, 4",
    description: "1 Ovo de Colher (Doce)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "38",
    customerName: "Milton Nascimento",
    deliveryDate: "2026-03-24",
    deliveryTime: "13:15",
    address: "Rua do Clube da Esquina, 0",
    description: "1 Ovo de Colher (Mineiro)",
    status: "Delivered",
    orderDate: "2026-03-22",
  },
  {
    id: "39",
    customerName: "Ney Matogrosso",
    deliveryDate: "2026-03-24",
    deliveryTime: "15:15",
    address: "Rua do Beija Flor, 66",
    description: "1 Ovo de Colher (Exótico)",
    status: "Pending",
    orderDate: "2026-03-21",
  },
  {
    id: "40",
    customerName: "Oscar Niemeyer",
    deliveryDate: "2026-03-24",
    deliveryTime: "11:45",
    address: "Rua das Curvas, 33",
    description: "1 Ovo Arquitetura 1kg",
    status: "Pending",
    orderDate: "2026-03-15",
  },
  {
    id: "41",
    customerName: "Paulo Coelho",
    deliveryDate: "2026-03-24",
    deliveryTime: "14:30",
    address: "Rua do Alquimista, 11",
    description: "1 Ovo de Colher (Místico)",
    status: "Delivered",
    orderDate: "2026-03-23",
  },
  {
    id: "42",
    customerName: "Rita Lee",
    deliveryDate: "2026-03-24",
    deliveryTime: "16:45",
    address: "Rua da Mutante, 77",
    description: "1 Ovo de Colher (Rock)",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "43",
    customerName: "Seu Jorge",
    deliveryDate: "2026-03-24",
    deliveryTime: "18:30",
    address: "Rua da Amiga da Minha Mulher, 44",
    description: "2 Ovos de Colher (Samba)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "44",
    customerName: "Tarsila do Amaral",
    deliveryDate: "2026-03-24",
    deliveryTime: "10:45",
    address: "Rua Abaporu, 1920",
    description: "1 Ovo de Colher (Arte)",
    status: "Delivered",
    orderDate: "2026-03-18",
  },
  {
    id: "45",
    customerName: "Vinicius de Moraes",
    deliveryDate: "2026-03-24",
    deliveryTime: "12:15",
    address: "Rua da Arca de Noé, 02",
    description: "1 Ovo de Colher (Poesia)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
  {
    id: "46",
    customerName: "Wilson das Neves",
    deliveryDate: "2026-03-25",
    deliveryTime: "14:00",
    address: "Rua do Império, 80",
    description: "1 Ovo de Colher (Bateria)",
    status: "Pending",
    orderDate: "2026-03-22",
  },
  {
    id: "47",
    customerName: "Xande de Pilares",
    deliveryDate: "2026-03-24",
    deliveryTime: "21:15",
    address: "Rua do Revelação, 12",
    description: "1 Ovo de Colher (Pagode)",
    status: "Pending",
    orderDate: "2026-03-21",
  },
  {
    id: "48",
    customerName: "Yoko Ono",
    deliveryDate: "2026-03-24",
    deliveryTime: "13:45",
    address: "Rua da Paz, 09",
    description: "1 Ovo de Colher (Conceitual)",
    status: "Delivered",
    orderDate: "2026-03-19",
  },
  {
    id: "49",
    customerName: "Zico",
    deliveryDate: "2026-03-24",
    deliveryTime: "19:15",
    address: "Rua do Maracanã, 10",
    description: "1 Ovo de Colher (Camisa 10)",
    status: "Pending",
    orderDate: "2026-03-20",
  },
  {
    id: "50",
    customerName: "Airton Senna",
    deliveryDate: "2026-03-24",
    deliveryTime: "08:15",
    address: "Rua da Vitória, 01",
    description: "1 Ovo de Colher (Veloz)",
    status: "Pending",
    orderDate: "2026-03-23",
  },
]

export function useOrders() {
  const [orders, setOrders] = useState<Order[]>(() => {
    const saved = localStorage.getItem("easter-orders")
    return saved ? JSON.parse(saved) : []
  })

  useEffect(() => {
    localStorage.setItem("easter-orders", JSON.stringify(orders))
  }, [orders])

  const seedOrders = () => {
    setOrders((prev) => {
      const existingIds = new Set(prev.map((o) => o.id))
      const uniqueMocks = mockOrders.filter((m) => !existingIds.has(m.id))
      return [...uniqueMocks, ...prev]
    })
  }

  const addOrder = (newOrder: Order) => {
    setOrders((prev) => [newOrder, ...prev])
  }

  const deleteOrder = (id: string) => {
    setOrders((prev) => prev.filter((order) => order.id !== id))
  }

  const updateStatus = (id: string, status: Order["status"]) => {
    setOrders((prev) =>
      prev.map((order) => (order.id === id ? { ...order, status } : order))
    )
  }

  return { orders, addOrder, deleteOrder, updateStatus, seedOrders }
}
